name: Execute test
on: [push]
jobs:
  executeTest:
    name: 'lint check'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/chckout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
